github: foxlet
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=QFXXKKAB2B9MA&item_name=macOS-Simple-KVM', 'https://commerce.coinbase.com/checkout/96dc5777-0abf-437d-a9b5-a78ae2c4c227']
